---
title: "SQL Assignment 6"
author: "Hannah Hardy"
format: html
editor: visual
---

```{r}
#| include: false
#load packages
pacman::p_load(tidyverse, DBI, duckdb, nycflights13)
```

## Part 1

**download files and set up connection**

```{r}
#download the file

url <- "https://data-science-master.github.io/lectures/data/flights.duckdb"

download.file(url, destfile = "./assignment-6-hannahihardy/flights.duckdb", mode = "wb")

#make connection

conn <- dbConnect(duckdb(), "./assignment-6-hannahihardy/flights.duckdb", read_only = TRUE)

#check connection

dbIsValid(conn)
```

**Part 1 a: list the first 10 rows of the flights table**

```{r}
dbGetQuery(conn, "SELECT * FROM flights LIMIT 10")
```

**Part 1 b: number of flights in the data set and for each carrier

```{r}
#count all flights in the dataset
count_allflights <- "SELECT COUNT(*) FROM flights"
dbGetQuery(conn, count_allflights)


#count flights by carrier 
count_flightsbycarrier <- "SELECT carrier, COUNT(*) FROM flights GROUP BY carrier ORDER BY COUNT(*) DESC"
dbGetQuery(conn, count_flightsbycarrier)
```

**Part c: average departure delay (dep_delay)

```{r}
avg_depdelay <- dbGetQuery(conn, "SELECT AVG(dep_delay) FROM flights")
print(avg_depdelay)
```

**Part d: find the top 5 destinations (dest) with the most flights**

```{r}
five_most_dest <- dbGetQuery(conn, "SELECT dest, COUNT(*) AS dest_count FROM flights GROUP BY dest ORDER BY dest_count DESC LIMIT 5")

print(five_most_dest)
```

**Part e: create a table showing (carrier and average arrival delay (arr_delay))**

```{r}
dbGetQuery(conn, "SELECT carrier, AVG(arr_delay) AS avg_arr_delay FROM flights GROUP BY carrier ORDER BY avg_arr_delay DESC")
```

